### ISSUE TITLE
Sending Roles from Controller to Template!

### ISSUE THREAD

**Issue by HannahJSwystun** [schaloner/deadbolt-2-java-examples#8]
Hi Steve,

This sample is working really fine, however, i encoutred a problem when sending roles parameters from controllers into template here is the bogue : 

**1- Let's see what is OK**

![ok](https://cloud.githubusercontent.com/assets/20491664/21749380/9e1daa50-d595-11e6-82ac-0110a8eb6b7a.png)

**2- Now let's see what's KO** 

![ko](https://cloud.githubusercontent.com/assets/20491664/21749500/63c0baf8-d597-11e6-94fb-8e9b16c2511f.png)

How can I send roles (roles required for @restrict tags in template ) from controller to template !!
I tried looping such as : 
@for(s <- list) { allOf(@s), }
but this is not acceptable inside @restrict !!   even there is a comma at the end of loop ....

Any idea please ? 

thank you so so so so much

**Comment by schaloner** [comment]
Hi Hannah,

you're mixing up strings with roles.  In a template, when you use `allOf`, `allOfGroup`, etc, these are functions that wrap the string roles, e.g. `"R1"`, in an array or a list to create the AND/OR functionality.  What you're providing is a definition where the role name is `"allOf(R1)"` instead of `"R1"`.

If you check the [sourcecode](https://github.com/schaloner/deadbolt-2-java/blob/master/code/app/be/objectify/deadbolt/java/views/restrict.scala.html#L6) for the `restrict` template you can see that `roles` is a List[Array[String]].  

The outer list defines the OR, the inner arrays define the ANDs.   Requiring `R1` and `R2` is

    List(Array(R1, R2))

There is a single array, and roles inside that array are required for access.

Requiring `R1` or `R2` is

    List(Array(R1), Array(R2))

(**Note** - this is psuedocode, not actual code!)

So, if you want to dynamically pass that set of role restrictions into the template, `List(Array(R1, R2))` would translate to Java as 

    final List<String[]> pageRolesAND = Collections.singletonList(new String[]{"R1", "R2"});

And `List(Array(R1), Array(R2))` would translate to Java as 

    final List<String[]> pageRolesOR = Arrays.asList(new String[]{"R1"}, new String[]{"R2"});

You then would no longer use `anyOf` in your template because you already have that List.

    @(user: AuthorisedUser,
        listComputers: List[Computer],
        computersAll: Int, computersR: Int, computersS: Int, computersIP: Int, n: Int,
       ppOr: List[Array[String]])
    
    @restrict(roles = ppOr) {
        // content
    }

**Comment by HannahJSwystun** [comment]
Hi Steve,
Thank you very much, thank you a thousand times for your well written documentation as well as 100% technical specific details.
The issue can be closed.
👍 💯
